version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "dep: "
    labels:
      - "Dependencies"
      - "Python"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "dep: "
    labels:
      - "Dependencies"
      - "GitHub Actions"
